# from https://nikitabobko.github.io/AeroSpace/config-examples#i3-like-config
# Reference: https://github.com/i3/i3/blob/next/etc/config

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']


start-at-login = true

[gaps]
inner.horizontal = 10
inner.vertical =   10
outer.left =       10
outer.bottom =     10
outer.top =        10
outer.right =      10

[mode.main.binding]
cmd-h = [] # Disable "hide application"
cmd-alt-h = [] # Disable "hide others"

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# Consider using 'join-with' command as a 'split' replacement if you want to enable normalizations
alt-g = 'join-with right'
alt-v = 'join-with down'

alt-f = 'fullscreen'

alt-s = 'layout v_accordion' # 'layout stacking' in i3
alt-w = 'layout h_accordion' # 'layout tabbed' in i3
alt-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

alt-shift-space = 'layout floating tiling' # 'floating toggle' in i3

# Not supported, because this command is redundant in AeroSpace mental model.
# See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
#alt-space = 'focus toggle_tiling_floating'

# `focus parent`/`focus child` are not yet supported, and it's not clear whether they
# should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
# alt-a = 'focus parent'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 10'
alt-f1 = 'workspace 11'
alt-f2 = 'workspace 12'
alt-f3 = 'workspace 13'
alt-f4 = 'workspace 14'
alt-f5 = 'workspace 15'
alt-f6 = 'workspace 16'
alt-f7 = 'workspace 17'
alt-f8 = 'workspace 18'
alt-f9 = 'workspace 19'


alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace 10'

alt-shift-11 = 'move-node-to-workspace 11'
alt-shift-12 = 'move-node-to-workspace 12'
alt-shift-13 = 'move-node-to-workspace 13'
alt-shift-14 = 'move-node-to-workspace 14'
alt-shift-15 = 'move-node-to-workspace 15'
alt-shift-16 = 'move-node-to-workspace 16'
alt-shift-17 = 'move-node-to-workspace 17'
alt-shift-18 = 'move-node-to-workspace 18'
alt-shift-19 = 'move-node-to-workspace 19'

alt-shift-c = 'reload-config'

alt-r = 'mode resize'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'

[[on-window-detected]]
if.app-id = 'net.kovidgoyal.kitty'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-id = 'com.microsoft.Outlook'
run = 'move-node-to-workspace 10'

[[on-window-detected]]
if.app-id = 'com.microsoft.Teams2'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = "com.mitchellh.ghostty"
run = [
  # FIX: this is a workaround for https://github.com/nikitabobko/AeroSpace/issues/68
  # this was also observed in:
  # - https://github.com/ghostty-org/ghostty/issues/1840
  # - https://github.com/ghostty-org/ghostty/issues/2006
  "layout floating",
  "move-node-to-workspace 1",
]
