vim.keymap.set('n', '<leader>ff', '<cmd>Telescope find_files<CR>', {})
vim.keymap.set('n', '<leader>fg', '<cmd>Telescope live_grep<CR>', {})
vim.keymap.set('n', '<leader>fb', '<cmd>Telescope buffers<CR>', {})
vim.keymap.set('n', '<leader>fh', '<cmd>Telescope help_tags<CR>', {})
vim.keymap.set('n', '<leader>fr', '<cmd>Telescope oldfiles<CR>', {})
